spring:
  port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/PlantSystem?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    mode: HTML5
    check-template: true
    servlet:
      content-type: text/html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
